### ISSUE TITLE
Ability to CC

### ISSUE THREAD

**Issue by klyVeso** [swiftmade/laravel-sendgrid-notification-channel#14]
I want to continue to use this package but I need a way to CC an additional email. Is this possible?

**Comment by aozisik** [comment]
Hi @klyVeso 

Glad to see you're using our package. We just released v2.5.0, which gives you a new method called `customize`. You can use it to fully customise the outgoing mail, including adding cc and bcc.

After upgrading, please turn to our readme for more info on this: [Full Access to the Sendgrid Mail Object
](https://github.com/swiftmade/laravel-sendgrid-notification-channel#full-access-to-the-sendgrid-mail-object)
