### ISSUE TITLE
Returning the mail object 

### ISSUE THREAD

**Issue by harrydoddnoble** [swiftmade/laravel-sendgrid-notification-channel#16]
What is the best way to retrieve the object that was sent so that it can be stored in the database for future reference?

I can see the customise method which gives me the Mail object but I only want to store this if it is successfully sent.

**Comment by anstapol** [comment]
Same story here, would love to be able to get the message id

**Comment by aozisik** [comment]
Hi all!

Thanks for the input. I think we could fix this by exposing the Sendgrid Response object through the `Illuminate\Notifications\Events\NotificationSent` event.

You could listen to this event, and the event object would have a response property (`SendGrid/Response`). This should contain the message id you need.

See #17 and let me know if that's what you were looking for.

**Comment by aozisik** [comment]
Closing this as it's possible to get the message id via the `Illuminate\Notifications\Events\NotificationSent` event as of v2.6.0. See #17
