### ISSUE TITLE
$emailAddress must be a string. Got: isaac@co.nz

### ISSUE THREAD

**Issue by isaacdarcilla** [swiftmade/laravel-sendgrid-notification-channel#18]
![image](https://github.com/swiftmade/laravel-sendgrid-notification-channel/assets/22732118/5be56105-5284-4242-9027-0b413bddd716)

**Comment by isaacdarcilla** [comment]
Default should be `$notifiable->email->value` instead of `$notifiable->email`.

**Comment by aozisik** [comment]
Hi @isaacdarcilla,

The readme was out of date. Actually we use the `routeNotificationFor('mail')` method. This is the correct interface method to use for notifiables, and it's expected to return the email address as a string. You might want to check your implementation of this method in the User class (or your notifiable model).

https://laravel.com/docs/10.x/notifications#customizing-the-recipient

In case you don't want to touch your model code, you can always add a custom "->to" directive and pass the email address that way instead. If you provide at least one "to" address to the SendGridMessage instance, the library will use that instead.

I'm closing this issue for now, but feel free to re-open if necessary.

**Comment by isaacdarcilla** [comment]
> Hi @isaacdarcilla,
> 
> The readme was out of date. Actually we use the `routeNotificationFor('mail')` method. This is the correct interface method to use for notifiables, and it's expected to return the email address as a string. You might want to check your implementation of this method in the User class (or your notifiable model).
> 
> https://laravel.com/docs/10.x/notifications#customizing-the-recipient
> 
> In case you don't want to touch your model code, you can always add a custom "->to" directive and pass the email address that way instead. If you provide at least one "to" address to the SendGridMessage instance, the library will use that instead.
> 
> I'm closing this issue for now, but feel free to re-open if necessary.

Thank you for  the details.

**Comment by aozisik** [comment]
Hi @isaacdarcilla,

This might not affect the specific issue that you encountered, but I just realised the `routeNotificationForMail` can also return an array (`['email_address' => 'name']`) as well.

I opened a PR for this, and will release this soon.
